<h2>My Principles</h2>

<h3>As a Listener</h3>

<p>Listening to music for me is, primarily, an intellectual activity. I can expect plenty of horrified people who are accustomed to the idea of music being emotional, spiritual or anything like that, and people who will say I am "cold", that I have no "feeling" and some crap like that. Well, here are the facts: intellectuality <em>does not negate</em> beauty, feeling, amusement and wonder. The biggest thing is, though, that I refuse to use, as a criterion of judgement, a notion so vague and imprecise as "emotion". "Emotion", to me, is many, many orders of magnitude more subjective than <em>intelligence</em>. You can't fake intelligence. Yes, you can try to fool the less cautious ones, but you can't fool everybody. But when it comes to <em>emotion</em>, though, you <em>can</em> definitely fool many people with an absolutely fake performance, just as much as you can fail to touch many people with a completely earnest performance merely because it is too different from what people expect.</p>

<p>Just consider, for a moment, the incredibly painstaking, meticulous and technical work that it takes to record a piece of music: it is not just a matter of the artist going there and "feeling it", and expecting the tape will capture that. It doesn't work that way: recording involved a lot of technical knowledge, a lot of hard, sometimes tedious work, many takes and retakes, countless laborious hours inside a studio, and even plenty of trial and error. How do you expect a process like that to capture "true emotion"? Yes, of course there can be a lot of energy, spontaneity and feeling in such performances, but they inevitably get buried under many layers of complex labour, not to mention unpleasant changes made to please the executives. So, if I consider the "feeling" and "emotion" such a subjective and vague, what is left? Simple: the creativity, the intelligence, the necessity of expression, in short, the artist's vision. And THAT is what matters to me; it matters not if the artist shed rivers of tears when recording the vocal take, because that might as well be a massive hoax; it also doesn't matter if the artist made the whole thing without seeming to emote at all, because maybe he was merely being absolutely professional and keeping his mind and heart focused. Yes, I <em>do</em> get touched and moved by music very often. and I <em>do</em> "feel" and "emote" when I listen to music, but those reactions are <em>mine</em> and exclusively mine, and I don't expect anyone else to relate to them. Those reactions are also defined by my own experience of life, my taste, my opinions and my beliefs. It is my belief that the artist only does roughly half of the job; the other half is completed by the audience; and THAT is the way I listen to music.</p>

<p>As for the purpose that I listen to music for, it's very simple: <em>fun</em>. Yes, just that. I have a nasty thing against the preaching that music is larger than life, that it is bigger than the world and more important than everything, because when you get down to the very core of it, we all listen to music to pass the time, to be entertained. Of course music can change our perceptions quite radically, can move us to joy or sadness or change significant parts of our lives, but those things are added bonuses; they are <em>secondary</em>, and you can never be sure when or how those things will happen. If you listen to every piece of music expecting a deeply spiritual experience, you're bound to be disappointed. Those things happen when you least expect them.</p>

<p>I'm not "diminishing" music by taking it as fun. I'm actually doing the opposite: I <em>value fun</em> a whole lot, and let's face it, we all do that. We all need fun, it is <em>necessary</em> for our lives, in whatever shape or form we can find it. I find fun through music, as well as many other things. I find fun in making and reviewing music as well, and those things are important. I cannot live without the fun that music gives me, and I don't take that as a bad thing at all! Music is fun, and it's fun for the brain; not for the heart. The heart is just a muscle, remember?</p>

<h3>As a Musician</h3>

<p>Art is, above everything, expression. And what do we express through art? Well... pretty much anything we want. Art can express an infinitude of things. But the problem is: will the listener understand what we are saying? My opinion is that there will <em>always</em> be someone who misunderstands what we do; and the only solution there is to that is to <em>take it as a good thing</em>.</p>

<p>Think: we have the choice to put words in our music, but words aren't always clear. Our spoken language isn't a perfect language, and when it comes to music, people can misunderstand it in countless ways: seeing irony where there isn't any, failing to see irony even when it's blatant, taking a joke at face value, seeing a serious comment as a silly joke and so on and on. My idea is that, instead of trying to communicate a "message" through music, my job is to <em>suggest things</em>. The brain is very sensitive to suggestion, and people who have active imaginations will have a field day with such suggestions and fly really high with them. The people who don't have such active imaginations probably won't go that far, but at least I'm giving them the opportunity to exercise them. With my music being instrumental, it's even easier to suggest: melodies, harmonies and sound do not have inherent meanings, even though our Western society has been educated to interpret such things as "major key = happy /minor key = sad". But there are many ways in which you can twist those notions and preconceptions, introducing atonality, ambiguity, contradictions and so on and on; this way, the suggestion becomes more complex and layered.</p>

<p>It isn't a perfect method, of course, because many people just go "what the hell is this shit?" and throw the music in the garbage bin without a second chance, but you can't avoid that. I'm not trying to adopt a perfect method, simply because there isn't any. My method just works for me, and I think it's, so far, the most open and versatile way to make music there is. I am happy with it.</p>

<p>So, what do I express with my music? I frankly don't know. All I know is, my music is not an image of myself. I don't expect people to recognise me through my music. Yes, parts of me are all over the music, as it is bound to happen, but I am not pouring my heart and feelings over what I do: I'm just saying things. Just <em>things</em>, things that will suggest images and sights to people. I want to point them at <em>the world</em>, not at myself. I want them to look at the window, not at my face. I'm not trying to attract attention, but to push it away. My music speaks about people, about characters, real and imaginary places, things that <em>you</em> may feel, but that not necessarily I feel or felt. I don't try to reflect my feelings and thoughts through the music, as I feel that would make it way too... restrictive, I guess. I want my music to be for <em>everyone</em>, not just for people who I believe can "relate" to me.</p>

<p>So, how do I come up with the compositions? Basically I don't throw out any ideas on the grounds that "I would never do this!". Say, if I come up with an idea for a <em>samba</em>, I will try to do it. If come up with, I don't know, a <em>hip hop</em> idea, I will chase it. I only throw out ideas that I consider to be truly crap. If I feel something is way too difficult for me to tackle, I will put it for later. But the thing is, I'm ready for anything, to change paradigms and styles anytime. I may make an album exclusively of abstract electronic music, then put out a piece for a tango orchestra, or, I don't know, a synthpop album. I don't discard any possibilities! As I listen to dozens of different things, I make myself ready to absorb the absurd and the extreme and to play around with it. That's how I do stuff, and it suits me just fine.</p>

<h3>As a Reviewer</h3>

<p>I'm not a clown, I'm not a comedian or a teller of jokes, so I'm not here to make you laugh. Yes, I do have a sense of humour and I may throw out a joke or two in my reviews, but those are merely a tangent of my purpose here. I'm here to talk about the music. If you want funny and hilarious texts, you can visit Mark Prindle, who is brilliant and a <em>truly</em> entertaining and brilliant writer, who is usually very succint about the music and sometimes barely speaks about it! But as much as I appreciate him and learn from him, that's not what I'm here for. I'm not good at that, so I won't tackle it. If I seem too serious or overbearing, well, I guess there is not much I can do. If my writing, though, is real crap and boring to read, I will certainly try to improve, as I'm not here to bore you!</p>

<p>In general, I'll try to speak to people who are not familiar with the stuff I am reviewing. I won't exclude those who are, but my reviews won't start right away speaking to people who already know the music by heart. If you've never heard [a]Abbey Road[/a] or [a]Dark Side of the Moon[/a], don't feel rejected from this site! Read right away, that's what I'm here for. If, on the other hand, you've heard every obscure and hard-to-find Stereolab song a thousand times and there's nothing new you could possibly learn about them, fear not! I'm also willing to share my opinions with you.</p>

<p>I try not to refer to other reviewers as well. This isn't a scientific paper, in which I have to provide dozens of references that show that I'm not making up crap on the spot; this is an OPINION website, and if I feel that other reviewers do a better job than me and I can't add anything of my own, I wouldn't be writing at all. I'm not neglecting or excluding their opinions; if you want to read them, go ahead! But I'm not saying that I will NEVER quote what they say; I may do it when it's extremely pertinent, but overall, this is <em>my</em> site.</p>

<p>I will talk openly about MY perceptions, MY opinions and MY beliefs regarding the music, and I Won't impose on my self the effort of adding "IMHO" after every sentence. Keep in mind these judgements are all PERSONAL opinions, even when I say them as if they were facts. Don't feel offended if I say something that completely contradicts everything you think. If, however, commit any factual mistakes, <em>please</em> correct me! I will be highly, highly thankful, as I don't want my reviews to be dead wrong or inaccurate, and I'm always open to accept contributions. And, yes, DO contribute! Even if you want to say the exact opposite of what I say. All opinions are welcome, as long as you don't insult anybody, such as myself or other reviewers. I will reserve myself the right to cut off any offensive reviews from myself; saying Mike Oldfield is a pretentious ass is not offensive; saying Michael Stipe is a fuckin' faggot who should die for his faggotry IS offensive and I will haunt you on your sleep. I will NOT, however, and I repeat, <em>I will NOT</em> remove comments simply due to disagreeing with them.</p>

<p>All in all, I'm here to have fun and I hope everyone has fun here as well. That is my main principle.</p>

<p><?=CHtml::link('Back', array('/'))?></p>